#ifndef USER_SYSCALL_H__INCLUDED
#define USER_SYSCALL_H__INCLUDED

enum Syscall {
    SYS_CREATE = 1,
    SYS_MYTID,
    SYS_MYPARENTID,
    SYS_PASS,
    SYS_EXIT,
    SYS_DESTROY,
    SYS_SEND,
    SYS_RECEIVE,
    SYS_REPLY,
    SYS_AWAITEVENT,
};

#endif // USER_SYSCALL_H__INCLUDED
